### ISSUE TITLE
Looks bad on mobile

### ISSUE THREAD

**Issue by AmitMY** [usablica/intro.js#769]
On mobile, the number of the step disappears, and the step is covering the overlay

**Comment by bozdoz** [comment]
Could you post an example?

**Comment by AmitMY** [comment]
Sure!
Here is on Nexus 6
![introjs com- nexus 6p](https://user-images.githubusercontent.com/5757359/31293303-6e1cc460-aadf-11e7-8a99-9ef2999487ea.png)

Above 480 width:
![introjs com-](https://user-images.githubusercontent.com/5757359/31293325-7f7c82d6-aadf-11e7-8f15-1d15bb0f2f5d.png)

**Comment by AmitMY** [comment]
@bozdoz Do you think this will be addressed soon?

**Comment by bozdoz** [comment]
The issue of the tooltip over the content should be resolved in #768.  The issue of the number missing: I don't even know how that's intended to work, so I can't speak on it. @afshinm

**Comment by AmitMY** [comment]
Thanks @bozdoz 
If you look at the second image, you can see the number 1 on the top left corner
This is not the case on the first image

**Comment by devvinodtk** [comment]
Similar issue I am facing is, the html element is not highlighted  when I move towards the end of the screen in mobile devices (iPhone 6 Plus Portrait View) 
![screen shot 2017-11-13 at 8 18 47 am](https://user-images.githubusercontent.com/33612837/32707711-dd76b922-c84b-11e7-9ec9-6af37747b1c4.png)
![screen shot 2017-11-13 at 8 19 07 am](https://user-images.githubusercontent.com/33612837/32707713-dd9e0de2-c84b-11e7-85e1-a78a1cc96d99.png)

Another issue is, the tooltip appears below the overlay when I move towards the end of the screen in mobile devices (iPhone 6 Plus landscape view).
![screen shot 2017-11-13 at 8 19 45 am](https://user-images.githubusercontent.com/33612837/32707707-d39a47b6-c84b-11e7-90f3-0158fac7a1c8.png)
![screen shot 2017-11-13 at 8 25 32 am](https://user-images.githubusercontent.com/33612837/32707778-42f84716-c84c-11e7-998f-1aa656216dd2.png)

**Comment by glubb92** [comment]
I am still facing the same issues with the overlapping (see AmitMY) and the disappearing (see devvinodtk) of the tooltips. I tested it on the iPhone 7 and iPhone X. Those issues coming up on both devices, but somehow on the iPhone X some tooltips are working, which are broken on the other one. 
Any thoughts?
